### PR TITLE
batstyx changes

### PR DESCRIPTION
**Pull request by Supergecki**
These are the changes made by batstyx.
Just to have the newest version in the original repository.

Thanks for all this work @batstyx!
PS: Is this already fully tested?

### CODE REVIEW

**Comment by batstyx** [comment]
I don't know about *fully tested*, but I've been running it in HDT pretty much daily since I started dev on my copy of it. I only flagged it pre-release as only me using it doesn't really count for particularly thorough beta-testing.

**Comment by Supergecki** [comment]
I'm also already testing it... Works fine for me (by now).
I don't really own that many cards that have a view in the plugin.
At least the Deathrattle view works fine with Nine Lives.
But a big thanks for all changes!

**Comment by chWolfgang** [comment]
I have most of the cards for HS (Wild and Standard). I am happy to test anything for this add-on. I have been using the new version with no problems. But I have not specifically tested everything. Please let me know what, if anything, would be helpful to test.

**Comment by batstyx** [comment]
I've created a v1.5.0 release with Tess Greymane (and a Soulwarden bug fix) so the two projects should be at feature parity (at least for now).

As you've created a local build and release you might want to change [README.md](https://github.com/RedHatter/Graveyard/blob/master/README.md) to remove the Build Status shield (which is pointing at the [batstyx appveyor build](https://ci.appveyor.com/project/batstyx/Graveyard)) and change the Latest Release shield to:-

`[Latest Release](https://github.com/RedHatter/Graveyard/releases)`

so that it points at RedHatter [Latest Release](https://github.com/RedHatter/Graveyard/releases) rather than at batstyx [Latest Release](https://github.com/batstyx/Graveyard/releases)

**Comment by Supergecki** [comment]
README.md was updated. Thanks for the tip!

Let me see @chWolfgang...
* The Caverns Below
* Da Undatakah and Twilight's Call (should work since Deathrattle view works)
* Kangor's Endless Army
* Psychopomp (should work since Resurrection view works)
* Witching Hour (in combination with transforming Choose One minions such as Druid of the Claw)

I already tested some cards. These work:
* Soulwarden
* Mulchmuncher
* Bodywrapper

I expect the old cards to work because nothing really changed on them.
Really thanks for testing!

**Comment by chWolfgang** [comment]
Okay,
I tested the 5 cards listed. All worked as intended. 

One thing I did notice, and I am not sure how it is supposed to work, but FLOBBIDINOUS FLOOP went into the Graveyard (listing) as himself. Not the beast I summoned him as. This may be how the game works.

If I get a chance, I will try to research this. I don't have time at the moment and I thought getting this report out wasn't worth waiting.

Happy to do anything else I can to help.

**Comment by Supergecki** [comment]
Hello there,
thanks for testing! It really helps.

This thing with Flobbidinous Floop seems to be something similar to the Polymorph bug #39.
As said there, the limitation doesn't lie in the scope of our plugin, but in the Deck Tracker itself. I think this could get really hard to solve.

I don't think there's anything to be tested at the moment.
See you at the tavern!

**Pull request merged**
